"""Add movie metadata tables

Revision ID: 932a0a90eb34
Revises: 18ee4436bfb5
Create Date: 2026-07-27 07:41:24.957901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932a0a90eb34'
down_revision: Union[str, Sequence[str], None] = '18ee4436bfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
