import React, { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { get, post, imageUrl } from "../services/api";
import { Card, Loading, Failure } from "../components/ui";
const useData = path => { const [d,setD]=useState(),[e,setE]=useState(); useEffect(()=>{setD(null);get(path).then(setD).catch(x=>setE(x.message))},[path]); return [d,e]; };
const Rail=({title,items=[]})=><section><h2>{title}</h2><div className="rail">{items.map(x=><Card key={x.id} movie={x}/>)}</div></section>;
export function Home(){const[d,e]=useData("/api/v1/home");if(e)return <Failure error={e}/>;if(!d)return <Loading/>;return <main><div className="hero"><p>Indian cinema, all in one place</p><h1>Find your next movie night.</h1><Link to="/discover">Explore movies</Link></div><Rail title="Trending" items={d.trending}/><Rail title="Popular" items={d.popular}/><Rail title="Latest releases" items={d.latest}/><Rail title="Coming soon" items={d.upcoming}/><Rail title="Recently added" items={d.recently_added}/></main>}
export function Discover({preset=""}){const[q,setQ]=useState(preset),[d,setD]=useState({items:[]}),[e,setE]=useState();const search=x=>{x?.preventDefault();get(`/api/v1/discover?q=${encodeURIComponent(q)}`).then(setD).catch(y=>setE(y.message))};useEffect(()=>search(),[]);return <main><h1>Discover movies</h1><form className="search" onSubmit={search}><input aria-label="Search movies and people" value={q} onChange={x=>setQ(x.target.value)} placeholder="Movies, actors, directors, keywords…"/><button>Search</button></form>{e&&<p>{e}</p>}<p>{d.total||0} movies found</p><div className="grid">{d.items.map(x=><Card key={x.id} movie={x}/>)}</div></main>}
export function Movie(){const{id}=useParams();const[d,e]=useData(`/api/v1/movies/${id}/detail`);if(e)return <Failure error={e}/>;if(!d)return <Loading/>;const m=d.movie;return <main className="detail"><img className="poster" src={imageUrl(m.poster_path)} alt={`${m.title} poster`}/><article><p>{m.release_date} · {m.runtime_minutes||"—"} min · {m.status||""}</p><h1>{m.title}</h1>{m.tagline&&<p>{m.tagline}</p>}<p>{m.overview}</p><h2>Watch legally</h2>{d.movie.ott?.map(x=><p key={x.provider}>{x.url?<a href={x.url}>{x.provider}</a>:x.provider} · {x.release_date||"being verified"}</p>)}<h2>Cast</h2><div className="people">{d.cast.map(x=><Link key={x.person_id} to={`/people/${x.person_id}`}>{x.name}<small>{x.character}</small></Link>)}</div><h2>Crew</h2><div className="people">{d.crew.map((x,i)=><Link key={i} to={`/people/${x.person_id}`}>{x.name}<small>{x.job||x.department}</small></Link>)}</div><h2>Release information</h2>{d.releases.map((x,i)=><p key={i}>{x.country}: {x.date} · {x.type}</p>)}</article></main>}
export function Person(){const{id}=useParams();const[d,e]=useData(`/api/v1/people/${id}`);if(e)return <Failure error={e}/>;if(!d)return <Loading/>;return <main><div className="detail"><img className="poster" src={imageUrl(d.profile_path)} alt={`${d.name} profile`}/><article><h1>{d.name}</h1><p>{d.department||"Film professional"}</p></article></div><h2>Filmography</h2><div className="grid">{d.filmography.map((x,i)=><div key={i}><Card movie={x.movie}/><small>{x.role}</small></div>)}</div></main>}
export function Calendar(){const{period}=useParams();const[d,e]=useData(`/api/v1/calendar/${period}`);if(e)return <Failure error={e}/>;if(!d)return <Loading/>;return <main><h1>{period.replaceAll("-"," ")}</h1><div className="grid">{d.items.map(x=><Card key={x.id} movie={x}/>)}</div></main>}
export function Request(){const[r,setR]=useState();const submit=e=>{e.preventDefault();post("/api/v1/movie-requests",Object.fromEntries(new FormData(e.target))).then(setR).catch(x=>setR({error:x.message}))};return <main><h1>Request a movie</h1><form className="request" onSubmit={submit}><input name="movie_name" required placeholder="Movie name"/><input name="email" type="email" required placeholder="Email"/><input name="release_year" type="number" placeholder="Release year"/><input name="language" placeholder="Language"/><textarea name="details" placeholder="Details"/><button>Submit request</button></form>{r&&<p>{r.error||`Request ${r.request_id} is ${r.status.toLowerCase()}.`}</p>}</main>}
export function Legal({title,children}){return <main><h1>{title}</h1><p>{children}</p></main>}
