import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const img=p=>p ? (p.startsWith('http')?p:`https://image.tmdb.org/t/p/w500${p}`) : '/placeholder.svg';
function Card({m}){return <a className="card" href={`/movies/${m.id}`}><img loading="lazy" src={img(m.poster_path)} alt={`${m.title} poster`} onError={e=>e.currentTarget.src='/placeholder.svg'}/><div><strong>{m.title}</strong><small>{m.release_date?.slice(0,4)||'Release date unknown'} · ★ {m.rating?.toFixed(1)||'—'}</small></div></a>}
function Rail({title,items=[]}){return <section><h2>{title}</h2><div className="rail">{items.map(m=><Card key={m.id} m={m}/>)}</div></section>}
function Home(){const [data,setData]=useState(); useEffect(()=>{fetch(`${API}/api/v1/home`).then(r=>r.json()).then(setData)},[]); if(!data)return <main className="loading">Loading Indian cinema…</main>;return <main><div className="hero"><p>Indian cinema, all in one place</p><h1>Find your next movie night.</h1><a href="/discover">Explore movies</a></div><Rail title="Trending now" items={data.trending}/><Rail title="Popular movies" items={data.popular}/><Rail title="Latest releases" items={data.latest}/><Rail title="Coming soon" items={data.upcoming}/></main>}
function Discover(){const [q,setQ]=useState('');const [data,setData]=useState({items:[]});const find=e=>{e?.preventDefault();fetch(`${API}/api/v1/discover?q=${encodeURIComponent(q)}`).then(r=>r.json()).then(setData)};useEffect(()=>find(),[]);return <main><h1>Discover movies</h1><form className="search" onSubmit={find}><input aria-label="Search movies and people" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search movies, actors, directors…"/><button>Search</button></form><p>{data.total||0} movies found</p><div className="grid">{data.items.map(m=><Card key={m.id} m={m}/>)}</div></main>}
function Movie(){let id=location.pathname.split('/').pop();const [m,setM]=useState();useEffect(()=>{Promise.all([fetch(`${API}/movies/${id}`).then(r=>r.json()),fetch(`${API}/movies/${id}/cast`).then(r=>r.json()),fetch(`${API}/movies/${id}/crew`).then(r=>r.json()),fetch(`${API}/movies/${id}/external-ids`).then(r=>r.json())]).then(([movie,cast,crew,externalIds])=>setM({...movie,cast,crew,externalIds}))},[id]);if(!m)return <main className="loading">Loading movie…</main>; document.title=`${m.title} | Indian OTT Tracker`;return <main className="detail"><img className="poster" src={img(m.poster_path)} alt={`${m.title} poster`}/><article><p>{m.release_date} · {m.runtime_minutes||'—'} min</p><h1>{m.title}</h1>{m.original_title&&<p>Original title: {m.original_title}</p>}<p className="rating">★ {m.vote_average?.toFixed(1)||'—'} <span>{m.vote_count||0} votes</span></p><p>{m.overview||'Overview is not available yet.'}</p><p>{m.genres?.map(g=>g.name).join(' · ')}</p><h2>Where to watch</h2>{m.ott_availability?.available?m.ott_availability.providers.map(p=><p key={p.name}>{`${p.name} (${p.watch_type})`}</p>):<p>OTT availability is being verified.</p>}<h2>Cast</h2><div className="people">{m.cast?.map(p=><a href={`/people/${p.person_id}`} key={p.person_id}>{p.name} <small>{p.character}</small></a>)}</div><h2>Crew</h2><div className="people">{m.crew?.map((p,i)=><a href={`/people/${p.person_id}`} key={i}>{p.name} <small>{p.job||p.department}</small></a>)}</div></article></main>}
function Person(){let id=location.pathname.split('/').pop();const [person,setPerson]=useState();const [error,setError]=useState();useEffect(()=>{fetch(`${API}/api/v1/people/${id}`).then(r=>{if(!r.ok)throw new Error('Person not found');return r.json()}).then(setPerson).catch(e=>setError(e.message))},[id]);if(error)return <main className="loading">{error}</main>;if(!person)return <main className="loading">Loading person…</main>;document.title=`${person.name} | Indian OTT Tracker`;return <main><div className="detail"><img className="poster" src={img(person.profile_path)} alt={`${person.name} profile`}/><article><h1>{person.name}</h1><p>{person.department||'Film professional'}</p></article></div><h2>Filmography</h2><div className="grid">{person.filmography.map((item,index)=><div key={index}><Card m={item.movie}/><small>{item.role}</small></div>)}</div></main>}
function Request(){const [result,setResult]=useState();const submit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));fetch(`${API}/api/v1/movie-requests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(r=>r.json()).then(setResult)};return <main><h1>Request a movie</h1><p>Couldn’t find a title? Send it to our editorial queue.</p><form className="request" onSubmit={submit}><input name="movie_name" required placeholder="Movie name"/><input name="email" type="email" required placeholder="Email address"/><input name="release_year" type="number" placeholder="Release year (optional)"/><input name="language" placeholder="Language (optional)"/><textarea name="details" placeholder="Additional details (optional)"/><button>Submit request</button></form>{result&&<p>Your request {result.request_id} is {result.status.toLowerCase()}.</p>}</main>}
function Legal({page}){return <main><h1>{page}</h1><p>Indian OTT Tracker helps visitors discover Indian movies and lawful streaming availability. Site, analytics, advertising and contact settings are configured by the operator before launch.</p><p>We only collect a requestor’s email to respond to their movie request; it is never displayed publicly. Contact the site operator to exercise applicable privacy rights.</p></main>}
function App(){let p=location.pathname;let content=p.startsWith('/movies/')?<Movie/>:p.startsWith('/people/')?<Person/>:p==='/discover'||p.startsWith('/search')?<Discover/>:p==='/request-movie'?<Request/>:['/about','/contact','/privacy','/terms','/cookies'].includes(p)?<Legal page={p.slice(1).replace(/^./,x=>x.toUpperCase())}/>:<Home/>;return <><header><a className="brand" href="/">Indian OTT Tracker</a><nav><a href="/discover">Discover</a><a target="_blank" rel="noreferrer" href="/request-movie">Request a movie</a></nav></header>{content}<footer><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/cookies">Cookies</a></footer></>};createRoot(document.getElementById('root')).render(<App/>);
